# Generated by Django 5.1.3 on 2025-01-07 06:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('web_design', 'Web Design'), ('graphic_design', 'Graphic Design'), ('video_editing', 'Video Editing'), ('online_marketing', 'Online Marketing'), ('development', 'Development'), ('foreign_language', 'Foreign Language Learning')], max_length=100, unique=True)),
                ('slug', models.SlugField(max_length=100, unique=True)),
            ],
        ),
    ]
